# Generated by Django 5.1.4 on 2025-01-05 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attrition', '0002_auto_20210504_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('emp_group', models.CharField(max_length=10)),
                ('function', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('tenure_group', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('hiring_source', models.CharField(max_length=50)),
                ('promoted', models.BooleanField()),
                ('job_role_match', models.BooleanField()),
                ('prediction_result', models.BooleanField()),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
