# Generated by Django 3.2.25 on 2025-01-14 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrition_table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_group', models.CharField(blank=True, max_length=20, null=True)),
                ('function', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('tenure_group', models.CharField(blank=True, default='< =1', max_length=10, null=True)),
                ('experience', models.FloatField(blank=True, default=0.0, null=True)),
                ('maritial', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.FloatField(blank=True, default=25.0, null=True)),
                ('hiring_source', models.CharField(max_length=40)),
                ('promoted_before', models.CharField(blank=True, max_length=40, null=True)),
                ('job_role', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_group', models.CharField(blank=True, max_length=10, null=True)),
                ('function', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('tenure_group', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('hiring_source', models.CharField(blank=True, max_length=50, null=True)),
                ('promoted', models.BooleanField(blank=True, null=True)),
                ('job_role_match', models.BooleanField(blank=True, null=True)),
                ('prediction_result', models.BooleanField(blank=True, null=True)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
