# Generated by Django 3.2.25 on 2025-01-14 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=100)),
                ('monthly_income', models.FloatField()),
                ('years_at_company', models.FloatField()),
                ('job_satisfaction', models.IntegerField()),
                ('work_life_balance', models.IntegerField()),
                ('prediction_result', models.BooleanField()),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
