# Generated by Django 3.2.25 on 2025-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_predictor', '0004_handle_auth_user_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='attritionprediction',
            name='risk_level',
            field=models.CharField(default='Medium Risk', max_length=20),
        ),
        migrations.AddField(
            model_name='attritionprediction',
            name='risk_score',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='emp_group',
            field=models.CharField(default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='function',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='hiring_source',
            field=models.CharField(default='Direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='job_role_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='marital_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='prediction_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attritionprediction',
            name='tenure_group',
            field=models.CharField(default='< =1', max_length=20),
        ),
    ]
